def register(runtime):
    runtime.register(
        "urioffice://{host}/query/status",
        "python://urioffice.handlers:status",
        kind="query",
        operation="office.status",
    )
    runtime.register(
        "urioffice://{host}/document/command/open",
        "python://urioffice.handlers:document_open",
        kind="command",
        operation="office.document.open",
        approval="required",
        side_effects=True,
    )
    runtime.register(
        "urioffice://{host}/document/command/save",
        "python://urioffice.handlers:document_save",
        kind="command",
        operation="office.document.save",
        approval="required",
        side_effects=True,
    )
    runtime.register(
        "urioffice://{host}/document/command/export-pdf",
        "python://urioffice.handlers:document_export_pdf",
        kind="command",
        operation="office.document.export_pdf",
        approval="required",
        side_effects=True,
    )
    runtime.register(
        "urioffice://{host}/writer/command/render",
        "python://urioffice.handlers:writer_render",
        kind="command",
        operation="office.writer.render",
        approval="required",
        side_effects=True,
    )
