flowchart LR
%% generated in 0.02s
    subgraph packages__python
        packages__python__urisysedge__runtime__load_json["load_json"]
        packages__python__urisysedge__runtime__load_yaml_flow["load_yaml_flow"]
        packages__python__urisysedge__runtime__JsonlEventStore__tail["tail"]
        packages__python__urisysedge__runtime__make_handler["make_handler"]
        packages__python__urisysedge__runtime__serve["serve"]
        packages__python__urisysedge__env__load_env_policy["load_env_policy"]
        packages__python__urisysedge__env___env_policy_candidates["_env_policy_candidates"]
        packages__python__urisysedge__env___urisys_root["_urisys_root"]
        packages__python__urisysedge__runtime__Runtime__call["call"]
        packages__python__urisysedge__env__load_urisys_env["load_urisys_env"]
        packages__python__urisysedge__env__is_secret_env["is_secret_env"]
        packages__python__urisysedge__env___env_config["_env_config"]
        packages__python__urisysedge__runtime__run_flow["run_flow"]
        packages__python__urisysedge__env__resolve_env_var["resolve_env_var"]
    end
    subgraph scripts__office_simulate_loop
        scripts__office_simulate_loop__call_uri["call_uri"]
        scripts__office_simulate_loop__parse_args["parse_args"]
        scripts__office_simulate_loop__rules_tick["rules_tick"]
        scripts__office_simulate_loop__main["main"]
        scripts__office_simulate_loop__llm_tick["llm_tick"]
    end
    subgraph scripts__report
        scripts__report__cli__main["main"]
        scripts__report__lab_checks___duplicate_recommendation["_duplicate_recommendation"]
        scripts__report__session_io__write_session_report["write_session_report"]
        scripts__report__session_markdown___environment_section["_environment_section"]
        scripts__report__events__merge_event_summaries["merge_event_summaries"]
        scripts__report__run_analysis__write_run_analysis["write_run_analysis"]
        scripts__report__session__generate_report["generate_report"]
        scripts__report__session_markdown__render_session_markdown["render_session_markdown"]
        scripts__report__session__infer_steps["infer_steps"]
        scripts__report__lab_checks__iter_step_results["iter_step_results"]
        scripts__report__session__session_duration["session_duration"]
        scripts__report__util__read_json["read_json"]
        scripts__report__session_markdown___steps_section["_steps_section"]
        scripts__report__events__summarize_events["summarize_events"]
        scripts__report__events__load_event_records["load_event_records"]
        scripts__report__util__now_iso["now_iso"]
        scripts__report__lab_checks__analyze_lab_flows["analyze_lab_flows"]
        scripts__report__run_analysis__analyze_run["analyze_run"]
        scripts__report__session_markdown___screenshots_section["_screenshots_section"]
        scripts__report__lab_checks__check_duplicate_screenshots["check_duplicate_screenshots"]
        scripts__report__lab_checks__load_flow_outcomes["load_flow_outcomes"]
        scripts__report__run_markdown__render_run_analysis_markdown["render_run_analysis_markdown"]
        scripts__report__events__summarize_event_records["summarize_event_records"]
    end
    subgraph scripts__run_nl_log_smoke
        scripts__run_nl_log_smoke__print["print"]
    end
    subgraph scripts__run_office_simulate_e2e
        scripts__run_office_simulate_e2e__wait_health["wait_health"]
    end
    subgraph scripts__run_office_simulate_lenovo
        scripts__run_office_simulate_lenovo__save_json["save_json"]
    end
    subgraph scripts__run_urisys_node_docker_e2e
        scripts__run_urisys_node_docker_e2e__remote_call["remote_call"]
        scripts__run_urisys_node_docker_e2e__http_json["http_json"]
    end
    subgraph scripts__test_sessions
        scripts__test_sessions__expectations___screen_changed["_screen_changed"]
        scripts__test_sessions__util__http_json["http_json"]
        scripts__test_sessions__expectations___screen_changed_since_previous["_screen_changed_since_previous"]
        scripts__test_sessions__expectations___opened_url_contains["_opened_url_contains"]
        scripts__test_sessions__expectations___min_vision_confidence["_min_vision_confidence"]
        scripts__test_sessions__lab_rdp__capture_rdp_screenshot_wait["capture_rdp_screenshot_wait"]
        scripts__test_sessions__lab_flows___capture_flow_screenshot["_capture_flow_screenshot"]
        scripts__test_sessions__util__wait_health["wait_health"]
        scripts__test_sessions__expectations__ocr_texts["ocr_texts"]
        scripts__test_sessions__lab_rdp__prepare_ok_target["prepare_ok_target"]
        scripts__test_sessions__util__write_meta["write_meta"]
        scripts__test_sessions__lab_rdp__capture_rdp_screenshot["capture_rdp_screenshot"]
        scripts__test_sessions__util__run_cmd["run_cmd"]
        scripts__test_sessions__lab_flows___flow_step_detail["_flow_step_detail"]
        scripts__test_sessions__util__compose_cmd["compose_cmd"]
        scripts__test_sessions__expectations__evaluate_expectations["evaluate_expectations"]
        scripts__test_sessions__util__docker_logs["docker_logs"]
        scripts__test_sessions__util__file_md5["file_md5"]
        scripts__test_sessions__lab_flows___lab_bootstrap["_lab_bootstrap"]
        scripts__test_sessions__util__copy_container_file["copy_container_file"]
        scripts__test_sessions__expectations___ocr_contains["_ocr_contains"]
        scripts__test_sessions__expectations__flow_expectations["flow_expectations"]
        scripts__test_sessions__util__now_iso["now_iso"]
        scripts__test_sessions__expectations__vision_confidences["vision_confidences"]
        scripts__test_sessions__util__finalize_session["finalize_session"]
        scripts__test_sessions__lab_flows__session_lab_10_flows["session_lab_10_flows"]
        scripts__test_sessions__util__read_meta["read_meta"]
        scripts__test_sessions__lab_flows___run_single_lab_flow["_run_single_lab_flow"]
        scripts__test_sessions__util__save_json["save_json"]
        scripts__test_sessions__util__sleep_ports["sleep_ports"]
    end
    subgraph src__urisys
        src__urisys__doctor___parse_version["_parse_version"]
        src__urisys__doctor___version_lt["_version_lt"]
        src__urisys__http_server___read_json["_read_json"]
        src__urisys__http_server__create_server["create_server"]
        src__urisys__managers__pack_manager__PackManager__manifest_paths["manifest_paths"]
        src__urisys__doctor___check_python["_check_python"]
        src__urisys__cli__print_json["print_json"]
        src__urisys__flow__load_flow["load_flow"]
        src__urisys__cli__build_parser["build_parser"]
        src__urisys__cli__resolve_markpact_source["resolve_markpact_source"]
        src__urisys__http_server___send["_send"]
        src__urisys__doctor___pkg_version["_pkg_version"]
        src__urisys__doctor___check_min_version["_check_min_version"]
        src__urisys__doctor___check_import["_check_import"]
        src__urisys__doctor___check_cli_path["_check_cli_path"]
        src__urisys__flow__iter_steps["iter_steps"]
        src__urisys__controllers__server_controller__ServerController____init__["__init__"]
        src__urisys__cli___add_runtime_flags["_add_runtime_flags"]
        src__urisys__cli__main["main"]
        src__urisys__doctor___check_wayland_him["_check_wayland_him"]
        src__urisys__controllers__flow_controller__FlowController__run["run"]
        src__urisys__controllers__server_controller__ServerController__serve_forever["serve_forever"]
        src__urisys__doctor__run_doctor["run_doctor"]
    end
    subgraph uribrowser_docker__packages
        uribrowser_docker__packages__python__uribrowseredge__cli__build_runtime["build_runtime"]
    end
    subgraph urienv_docker__packages
        urienv_docker__packages__python__urienv__src__urienv__handlers___cfg["_cfg"]
        urienv_docker__packages__python__urienv__src__urienv__handlers___read_docker_secret["_read_docker_secret"]
        urienv_docker__packages__python__urisysedge__src__urisysedge__pack_loader__manifest_paths["manifest_paths"]
        urienv_docker__packages__python__urisysedge__src__urisysedge__runtime__load_device_config["load_device_config"]
        urienv_docker__packages__python__urienv__src__urienv__handlers__var_set["var_set"]
        urienv_docker__packages__python__urisysedge__src__urisysedge__pack_loader__manifest_path_for_pack["manifest_path_for_pack"]
        urienv_docker__packages__python__urienv__src__urienv__handlers__var_unset["var_unset"]
        urienv_docker__packages__python__urisysedge__src__urisysedge__runtime__load_env_config["load_env_config"]
        urienv_docker__packages__python__urienv__src__urienv__handlers__startup_config["startup_config"]
        urienv_docker__packages__python__urienv__src__urienv__handlers___require_visible["_require_visible"]
        urienv_docker__packages__python__urienv__src__urienv__handlers___mask["_mask"]
        urienv_docker__packages__python__urienv__src__urienv__handlers__health["health"]
        urienv_docker__packages__python__urienv__src__urienv__handlers___split_csv["_split_csv"]
        urienv_docker__packages__python__urisysedge__src__urisysedge__flow__run_flow["run_flow"]
        urienv_docker__packages__python__urisysedge__src__urisysedge__runtime__result_to_dict["result_to_dict"]
        urienv_docker__packages__python__urisysedge__src__urisysedge__runtime__build_runtime["build_runtime"]
        urienv_docker__packages__python__urienv__src__urienv__handlers___is_secret["_is_secret"]
        urienv_docker__packages__python__urienv__src__urienv__handlers___is_mutable["_is_mutable"]
        urienv_docker__packages__python__urienv__src__urienv__handlers__var_exists["var_exists"]
        urienv_docker__packages__python__urienv__src__urienv__handlers__secret_value["secret_value"]
        urienv_docker__packages__python__urienv__src__urienv__handlers__secret_masked["secret_masked"]
        urienv_docker__packages__python__urienv__src__urienv__handlers___is_public["_is_public"]
        urienv_docker__packages__python__urienv__src__urienv__handlers___name["_name"]
        urienv_docker__packages__python__urisysedge__src__urisysedge__server__serve["serve"]
        urienv_docker__packages__python__urienv__src__urienv__handlers__var_value["var_value"]
        urienv_docker__packages__python__urienv__src__urienv__handlers___get_value["_get_value"]
        urienv_docker__packages__python__urienv__src__urienv__handlers__list_vars["list_vars"]
    end
    subgraph urikvm_docker__packages
        urikvm_docker__packages__python__uriocr__handlers___ocr_cfg["_ocr_cfg"]
        urikvm_docker__packages__python__urikvm__handlers___store_screenshot["_store_screenshot"]
        urikvm_docker__packages__python__urihim__handlers__mouse_scroll["mouse_scroll"]
        urikvm_docker__packages__python__urihim__handlers__mouse_click["mouse_click"]
        urikvm_docker__packages__python__urihim__handlers___real_allowed["_real_allowed"]
        urikvm_docker__packages__python__urihim__handlers___xdotool_available["_xdotool_available"]
        urikvm_docker__packages__python__uriocr__handlers___tesseract_boxes["_tesseract_boxes"]
        urikvm_docker__packages__python__uriocr__handlers__latest_text["latest_text"]
        urikvm_docker__packages__python__urihim__handlers___run_xdotool["_run_xdotool"]
        urikvm_docker__packages__python__urihim__handlers__keyboard_hotkey["keyboard_hotkey"]
        urikvm_docker__packages__python__urikvmedge__cli__build_runtime["build_runtime"]
        urikvm_docker__packages__python__uriocr__handlers__image_text["image_text"]
        urikvm_docker__packages__python__urihim__handlers___wayland_session["_wayland_session"]
        urikvm_docker__packages__python__urikvm__handlers___profile["_profile"]
        urikvm_docker__packages__python__urihim__handlers___ydotool_key_sequence["_ydotool_key_sequence"]
        urikvm_docker__packages__python__uriocr__handlers___png_bytes["_png_bytes"]
        urikvm_docker__packages__python__uriocr__handlers___latest_screenshot["_latest_screenshot"]
        urikvm_docker__packages__python__uriocr__handlers___mock_boxes["_mock_boxes"]
        urikvm_docker__packages__python__uriocr__handlers___driver["_driver"]
        urikvm_docker__packages__python__uriocr__handlers___merge_word_boxes["_merge_word_boxes"]
        urikvm_docker__packages__python__urikvm__handlers__monitor_list["monitor_list"]
        urikvm_docker__packages__python__urihim__handlers___pyautogui["_pyautogui"]
        urikvm_docker__packages__python__urihim__handlers___driver["_driver"]
        urikvm_docker__packages__python__urihim__handlers__keyboard_type["keyboard_type"]
        urikvm_docker__packages__python__urihim__handlers___state["_state"]
        urikvm_docker__packages__python__urihim__handlers___ydotool_available["_ydotool_available"]
        urikvm_docker__packages__python__urihim__handlers__mouse_status["mouse_status"]
        urikvm_docker__packages__python__uriocr__handlers___extract_text["_extract_text"]
        urikvm_docker__packages__python__urikvm__handlers__screenshot["screenshot"]
        urikvm_docker__packages__python__urihim__handlers___run_ydotool["_run_ydotool"]
        urikvm_docker__packages__python__urihim__handlers__mouse_move["mouse_move"]
    end
    subgraph urikvm_docker__scripts
        urikvm_docker__scripts__real_pipeline__build_runtime["build_runtime"]
        urikvm_docker__scripts__real_pipeline__main["main"]
    end
    subgraph urirdp_docker__packages
        urirdp_docker__packages__python__urirdp_kvm__display__config_value["config_value"]
        urirdp_docker__packages__python__urirdp_ocr__handlers__latest_text["latest_text"]
        urirdp_docker__packages__python__urirdpedge__cli__build_runtime["build_runtime"]
        urirdp_docker__packages__python__urirdp_him__handlers__keyboard_hotkey["keyboard_hotkey"]
        urirdp_docker__packages__python__urirdp__handlers__dismiss_target["dismiss_target"]
        urirdp_docker__packages__python__urirdp_llm__handlers___decide_messages["_decide_messages"]
        urirdp_docker__packages__python__urirdp_him__handlers__keyboard_type["keyboard_type"]
        urirdp_docker__packages__python__urirdp_ocr__handlers___tesseract_ocr["_tesseract_ocr"]
        urirdp_docker__packages__python__urirdp_browser__handlers___profile["_profile"]
        urirdp_docker__packages__python__urirdp_kvm__handlers__display_info["display_info"]
        urirdp_docker__packages__python__urirdp__handlers__display_status["display_status"]
        urirdp_docker__packages__python__urirdp_llm__handlers___target["_target"]
        urirdp_docker__packages__python__urirdp_llm__handlers___litellm_chat["_litellm_chat"]
        urirdp_docker__packages__python__urirdp_browser__handlers___chromium_binary["_chromium_binary"]
        urirdp_docker__packages__python__urirdp_shell__handlers___detect_display["_detect_display"]
        urirdp_docker__packages__python__urirdp_him__handlers__keyboard_key["keyboard_key"]
        urirdp_docker__packages__python__urirdp_him__handlers__keyboard_type_text["keyboard_type_text"]
        urirdp_docker__packages__python__urirdp_kvm__display__detect_display["detect_display"]
        urirdp_docker__packages__python__urirdp_kvm__display__run_cmd["run_cmd"]
        urirdp_docker__packages__python__urirdp_llm__handlers__analyze["analyze"]
        urirdp_docker__packages__python__urirdp_llm__handlers___env["_env"]
        urirdp_docker__packages__python__urirdp_llm__handlers___vision_messages["_vision_messages"]
        urirdp_docker__packages__python__urirdp_browser__handlers___session_state["_session_state"]
        urirdp_docker__packages__python__urirdp__handlers__status["status"]
        urirdp_docker__packages__python__urirdp_llm__handlers___llm_cfg["_llm_cfg"]
        urirdp_docker__packages__python__urirdp_llm__handlers___heuristic["_heuristic"]
        urirdp_docker__packages__python__urirdp__handlers__prepare_target["prepare_target"]
        urirdp_docker__packages__python__urirdp_him__handlers__mouse_move["mouse_move"]
        urirdp_docker__packages__python__urirdp_kvm__display__base_env["base_env"]
        urirdp_docker__packages__python__urirdp_ocr__handlers___parse_tesseract_tsv["_parse_tesseract_tsv"]
        urirdp_docker__packages__python__urirdp_him__handlers__mouse_click["mouse_click"]
        urirdp_docker__packages__python__urirdp_llm__handlers__decide["decide"]
        urirdp_docker__packages__python__urirdp__handlers___dismiss_stale_targets["_dismiss_stale_targets"]
        urirdp_docker__packages__python__urirdp__handlers__display["display"]
        urirdp_docker__packages__python__urirdp_llm__handlers___config["_config"]
        urirdp_docker__packages__python__urirdp_llm__handlers___screenshot_b64["_screenshot_b64"]
        urirdp_docker__packages__python__urirdp_ocr__handlers___mock_ocr["_mock_ocr"]
        urirdp_docker__packages__python__urirdp_ocr__handlers__image_text["image_text"]
        urirdp_docker__packages__python__urirdp_him__handlers___mock["_mock"]
        urirdp_docker__packages__python__urirdp_llm__handlers___openai_compatible_chat["_openai_compatible_chat"]
        urirdp_docker__packages__python__urirdp_shell__handlers__shell_run["shell_run"]
        urirdp_docker__packages__python__urirdp_llm__handlers___parse_json_response["_parse_json_response"]
        urirdp_docker__packages__python__urirdp_shell__handlers___mock["_mock"]
        urirdp_docker__packages__python__urirdp_llm__handlers__plan["plan"]
        urirdp_docker__packages__python__urirdp_browser__handlers__open_page["open_page"]
        urirdp_docker__packages__python__urirdp_kvm__handlers__screenshot["screenshot"]
        urirdp_docker__packages__python__urirdp_kvm__display__ensure_screenshot_dir["ensure_screenshot_dir"]
        urirdp_docker__packages__python__urirdp_llm__handlers___match_transcript["_match_transcript"]
        urirdp_docker__packages__python__urirdp_llm__handlers___decide_openai["_decide_openai"]
        urirdp_docker__packages__python__urirdp_kvm__display__allow_real["allow_real"]
        urirdp_docker__packages__python__urirdp__handlers___service_status["_service_status"]
        urirdp_docker__packages__python__urirdp_llm__handlers___decide_litellm["_decide_litellm"]
    end
    subgraph uristepper_docker__packages
        uristepper_docker__packages__python__uristepper__drivers__make_driver["make_driver"]
        uristepper_docker__packages__python__uristepperedge__runtime__build_runtime["build_runtime"]
        uristepper_docker__packages__python__uristepperedge__cli__cmd_routes["cmd_routes"]
        uristepper_docker__packages__python__uristepperedge__runtime__load_json["load_json"]
        uristepper_docker__packages__python__uristepperedge__server__serve["serve"]
        uristepper_docker__packages__python__uristepperedge__cli__cmd_explain["cmd_explain"]
        uristepper_docker__packages__python__uristepper__handlers__stop["stop"]
        uristepper_docker__packages__python__uristepperedge__cli___json_arg["_json_arg"]
        uristepper_docker__packages__python__uristepper__handlers___driver["_driver"]
        uristepper_docker__packages__python__uristepper__handlers__move_relative["move_relative"]
        uristepper_docker__packages__python__uristepper__handlers__move_absolute["move_absolute"]
        uristepper_docker__packages__python__uristepper__handlers___dry_or_driver["_dry_or_driver"]
        uristepper_docker__packages__python__uristepper__handlers__disable["disable"]
        uristepper_docker__packages__python__uristepper__handlers__enable["enable"]
        uristepper_docker__packages__python__uristepper__handlers___device_axis["_device_axis"]
        uristepper_docker__packages__python__uristepper__handlers___enforce_safety["_enforce_safety"]
        uristepper_docker__packages__python__uristepperedge__cli__cmd_serve["cmd_serve"]
        uristepper_docker__packages__python__uristepperedge__cli__cmd_flow["cmd_flow"]
        uristepper_docker__packages__python__uristepper__handlers__status["status"]
        uristepper_docker__packages__python__uristepperedge__cli__cmd_call["cmd_call"]
        uristepper_docker__packages__python__uristepperedge__cli__cmd_events["cmd_events"]
        uristepper_docker__packages__python__uristepper__handlers__home["home"]
        uristepper_docker__packages__python__uristepperedge__server__make_handler["make_handler"]
    end
    subgraph urisys_automation_lab__packages
        urisys_automation_lab__packages__python__uriwebrtc__handlers__session_start["session_start"]
        urisys_automation_lab__packages__python__urichat__handlers__uri_execute["uri_execute"]
        urisys_automation_lab__packages__python__uristt__handlers__session_transcript["session_transcript"]
        urisys_automation_lab__packages__python__uristt__handlers___session_id["_session_id"]
        urisys_automation_lab__packages__python__uriwebrtc__handlers__data_send["data_send"]
        urisys_automation_lab__packages__python__uristt__handlers__session_start["session_start"]
        urisys_automation_lab__packages__python__uriwebrtc__handlers___room_id["_room_id"]
        urisys_automation_lab__packages__python__urichat__handlers___forward_uri["_forward_uri"]
    end
    subgraph urisys_automation_lab__server
        urisys_automation_lab__server__flow_runner__plan_flow["plan_flow"]
        urisys_automation_lab__server__flow_runner___lab_adapter_session["_lab_adapter_session"]
        urisys_automation_lab__server__flow_runner__run_flow_file["run_flow_file"]
        urisys_automation_lab__server__flow_runner___load_defaults["_load_defaults"]
        urisys_automation_lab__server__flow_runner___require_uri_stack["_require_uri_stack"]
        urisys_automation_lab__server__automation_lab_server__build_lab_runtime["build_lab_runtime"]
        urisys_automation_lab__server__automation_lab_server__LabHandler__log_message["log_message"]
        urisys_automation_lab__server__automation_lab_server__serve["serve"]
        urisys_automation_lab__server__lab_uri_adapter__step_ok["step_ok"]
        urisys_automation_lab__server__lab_uri_adapter__LabCallAdapter__execute["execute"]
    end
    subgraph urisys_automation_lab__web
        urisys_automation_lab__web__app__rec["rec"]
        urisys_automation_lab__web__app__text["text"]
        urisys_automation_lab__web__app__uriCall["uriCall"]
        urisys_automation_lab__web__app__log["log"]
        urisys_automation_lab__web__app__SR["SR"]
        urisys_automation_lab__web__app__data["data"]
    end
    subgraph urisys_node__packages
        urisys_node__packages__python__urisysnode__identity__health_payload["health_payload"]
        urisys_node__packages__python__urisysnode__serve__call_uri["call_uri"]
        urisys_node__packages__python__uriscreen__handlers__frame["frame"]
        urisys_node__packages__python__urisysnode__display_bootstrap___agent_url["_agent_url"]
        urisys_node__packages__python__uriscreen__backends__resolve_backend["resolve_backend"]
        urisys_node__packages__python__uriscreen__backends__is_wayland["is_wayland"]
        urisys_node__packages__python__urisysnode__artifact_resolver__contract_url_from_release["contract_url_from_release"]
        urisys_node__packages__python__uriscreen__backends__capture_vdisplay["capture_vdisplay"]
        urisys_node__packages__python__urisysnode__identity___identity_path["_identity_path"]
        urisys_node__packages__python__urisysnode__artifact_resolver__run_release["run_release"]
        urisys_node__packages__python__urisysnode__display_bootstrap___start_agent["_start_agent"]
        urisys_node__packages__python__urisysnode__forward_config__load_release_forward_entries["load_release_forward_entries"]
        urisys_node__packages__python__uriscreen__backends___http_json["_http_json"]
        urisys_node__packages__python__urisysnode__handlers__command_register_forward["command_register_forward"]
        urisys_node__packages__python__urisysnode__identity__enroll["enroll"]
        urisys_node__packages__python__urisysnode__display_bootstrap___start_screencast["_start_screencast"]
        urisys_node__packages__python__urisysnode__artifact_resolver___contract_yaml_block["_contract_yaml_block"]
        urisys_node__packages__python__urisysnode__pack_resolver__github_owner["github_owner"]
        urisys_node__packages__python__urisysnode__artifact_resolver__fetch_text["fetch_text"]
        urisys_node__packages__python__urisysnode__router__load_route_map["load_route_map"]
        urisys_node__packages__python__urisysnode__identity__require_paired["require_paired"]
        urisys_node__packages__python__urisysnode__forward_config___normalize_entry["_normalize_entry"]
        urisys_node__packages__python__urisysnode__identity___data_dir["_data_dir"]
        urisys_node__packages__python__uriscreen__backends__is_black_png["is_black_png"]
        urisys_node__packages__python__urisysnode__router__node_endpoint["node_endpoint"]
        urisys_node__packages__python__urishell__handlers___detect_display["_detect_display"]
        urisys_node__packages__python__urisysnode__router__resolve_remote_route["resolve_remote_route"]
        urisys_node__packages__python__uriscreen__handlers___output_dir["_output_dir"]
        urisys_node__packages__python__urisysnode__client__remote_call["remote_call"]
        urisys_node__packages__python__urisysnode__artifact_resolver__wait_health["wait_health"]
        urisys_node__packages__python__urisysnode__pack_resolver__pack_importable["pack_importable"]
        urisys_node__packages__python__uriscreen__handlers___monitor_index["_monitor_index"]
        urisys_node__packages__python__urisysnode__artifact_resolver__load_artifact_index["load_artifact_index"]
        urisys_node__packages__python__urisysnode__serve__hotload_release_pack["hotload_release_pack"]
        urisys_node__packages__python__uriscreen__backends__vdisplay_agent_up["vdisplay_agent_up"]
        urisys_node__packages__python__urisysnode__artifact_resolver___auth_opener["_auth_opener"]
        urisys_node__packages__python__uriscreen__handlers__capture_loop["capture_loop"]
        urisys_node__packages__python__urisysnode__pack_resolver__pack_for_scheme["pack_for_scheme"]
        urisys_node__packages__python__urisysnode__handlers__command_indicator_off["command_indicator_off"]
        urisys_node__packages__python__urisysnode__identity__load_identity["load_identity"]
        urisys_node__packages__python__urisysnode__artifact_resolver__docker_run_worker["docker_run_worker"]
        urisys_node__packages__python__uriscreen__handlers___store_latest["_store_latest"]
        urisys_node__packages__python__urisysnode__handlers__query_identity["query_identity"]
        urisys_node__packages__python__urisysnode__client__call_via_route_map["call_via_route_map"]
        urisys_node__packages__python__urisysnode__artifact_resolver__resolve_from_release["resolve_from_release"]
        urisys_node__packages__python__urisysnode__serve___extend_pack_paths["_extend_pack_paths"]
        urisys_node__packages__python__urisysnode__serve__ensure_pack_for_uri["ensure_pack_for_uri"]
        urisys_node__packages__python__urisysnode__display_bootstrap___screencast_ready["_screencast_ready"]
        urisys_node__packages__python__uriscreen__backends__session_type["session_type"]
        urisys_node__packages__python__urisysnode__artifact_resolver__fetch_release["fetch_release"]
        urisys_node__packages__python__urisysnode__forward_config___normalize_release_entry["_normalize_release_entry"]
        urisys_node__packages__python__urisysnode__identity__save_pairing["save_pairing"]
        urisys_node__packages__python__urisysnode__release_verify__signature_required["signature_required"]
        urisys_node__packages__python__urisysnode__artifact_resolver__parse_contract_spec["parse_contract_spec"]
        urisys_node__packages__python__urisysnode__pack_resolver__scheme_for_uri["scheme_for_uri"]
        urisys_node__packages__python__uriscreen__portal_capture__capture_portal_png["capture_portal_png"]
        urisys_node__packages__python__urisysnode__release_verify___ed25519_verify["_ed25519_verify"]
        urisys_node__packages__python__urisysnode__identity__load_pairing["load_pairing"]
        urisys_node__packages__python__urisysnode__router__rewrite_uri_for_slave["rewrite_uri_for_slave"]
        urisys_node__packages__python__urisysnode__identity__set_remote_control["set_remote_control"]
        urisys_node__packages__python__uriscreen__handlers___screen_cfg["_screen_cfg"]
        urisys_node__packages__python__urisysnode__handlers__command_install_pack["command_install_pack"]
        urisys_node__packages__python__urisysnode__artifact_resolver__contract_spec_from_release["contract_spec_from_release"]
        urisys_node__packages__python__urisysnode__identity__save_identity["save_identity"]
        urisys_node__packages__python__urisysnode__display_bootstrap__bootstrap_wayland_capture["bootstrap_wayland_capture"]
        urisys_node__packages__python__urisysnode__handlers__command_indicator_on["command_indicator_on"]
        urisys_node__packages__python__uriscreen__backends__vdisplay_agent_url["vdisplay_agent_url"]
        urisys_node__packages__python__urisysnode__artifact_resolver__release_api_url["release_api_url"]
        urisys_node__packages__python__uriscreen__backends__vdisplay_screencast_ready["vdisplay_screencast_ready"]
        urisys_node__packages__python__urisysnode__serve__register_forward_pack["register_forward_pack"]
        urisys_node__packages__python__urisysnode__display_bootstrap___agent_up["_agent_up"]
        urisys_node__packages__python__urisysnode__serve__load_pack_into_runtime["load_pack_into_runtime"]
        urisys_node__packages__python__urisysnode__serve__build_runtime["build_runtime"]
        urisys_node__packages__python__uriscreen__backends__capture_portal["capture_portal"]
        urisys_node__packages__python__urisysnode__artifact_resolver__fetch_json["fetch_json"]
        urisys_node__packages__python__urisysnode__release_verify__verify_release["verify_release"]
        urisys_node__packages__python__urisysnode__artifact_resolver__resolve_and_run["resolve_and_run"]
        urisys_node__packages__python__urisysnode__artifact_resolver__docker_pull["docker_pull"]
        urisys_node__packages__python__uriscreen__handlers___backend["_backend"]
        urisys_node__packages__python__urisysnode__forward_config__wire_forward_packs["wire_forward_packs"]
        urisys_node__packages__python__urisysnode__forward_config__load_forward_entries["load_forward_entries"]
        urisys_node__packages__python__urisysnode__handlers__query_packs["query_packs"]
        urisys_node__packages__python__urisysnode__router___match_pattern["_match_pattern"]
        urisys_node__packages__python__urisysnode__pack_resolver__resolve_pack_spec["resolve_pack_spec"]
        urisys_node__packages__python__urisysnode__forward_config__wire_release_forward_packs["wire_release_forward_packs"]
        urisys_node__packages__python__urisysnode__artifact_resolver__select_artifact["select_artifact"]
        urisys_node__packages__python__urisysnode__serve___register_pack["_register_pack"]
        urisys_node__packages__python__uriscreen__backends__capture_with_fallback["capture_with_fallback"]
        urisys_node__packages__python__urisysnode__serve__serve["serve"]
        urisys_node__packages__python__urisysnode__release_verify__canonical_digest["canonical_digest"]
        urisys_node__packages__python__urishell__handlers__shell_run["shell_run"]
        urisys_node__packages__python__urisysnode__artifact_resolver__load_node_profile["load_node_profile"]
        urisys_node__packages__python__urisysnode__display_bootstrap___ensure_session_env["_ensure_session_env"]
        urisys_node__packages__python__urisysnode__serve__make_handler["make_handler"]
        urisys_node__packages__python__uriscreen__handlers__capture["capture"]
        urisys_node__packages__python__urisysnode__identity___hostname["_hostname"]
        urisys_node__packages__python__urisysnode__pack_resolver__github_wheel_url["github_wheel_url"]
        urisys_node__packages__python__urisysnode__pack_resolver__auto_install_enabled["auto_install_enabled"]
        urisys_node__packages__python__urisysnode__serve___release_forward_spec["_release_forward_spec"]
        urisys_node__packages__python__uriscreen__portal_capture___portal_python["_portal_python"]
        urisys_node__packages__python__urisysnode__identity___pairing_path["_pairing_path"]
        urisys_node__packages__python__urisysnode__pack_resolver__ensure_pack_pypi["ensure_pack_pypi"]
        urisys_node__packages__python__urisysnode__forward__forward_call["forward_call"]
        urisys_node__packages__python__urisysnode__handlers__query_health["query_health"]
        urisys_node__packages__python__urisysnode__artifact_resolver__is_url["is_url"]
        urisys_node__packages__python__urishell__handlers___mock["_mock"]
    end
    packages__python__urisysedge__runtime__Runtime__call --> packages__python__urisysedge__env__load_env_policy
    packages__python__urisysedge__runtime__run_flow --> packages__python__urisysedge__runtime__load_yaml_flow
    packages__python__urisysedge__runtime__serve --> scripts__run_nl_log_smoke__print
    packages__python__urisysedge__runtime__serve --> packages__python__urisysedge__runtime__make_handler
    packages__python__urisysedge__env__load_urisys_env --> packages__python__urisysedge__env___urisys_root
    packages__python__urisysedge__env___env_policy_candidates --> packages__python__urisysedge__env___urisys_root
    packages__python__urisysedge__env__load_env_policy --> packages__python__urisysedge__env___env_policy_candidates
    packages__python__urisysedge__env__resolve_env_var --> packages__python__urisysedge__env___env_config
    packages__python__urisysedge__env__resolve_env_var --> packages__python__urisysedge__env__load_env_policy
    packages__python__urisysedge__env__resolve_env_var --> urienv_docker__packages__python__urienv__src__urienv__handlers__secret_value
    packages__python__urisysedge__env__resolve_env_var --> urienv_docker__packages__python__urienv__src__urienv__handlers__var_value
    src__urisys__cli__print_json --> scripts__run_nl_log_smoke__print
    src__urisys__cli__build_parser --> src__urisys__cli___add_runtime_flags
    src__urisys__cli__main --> src__urisys__cli__build_parser
    src__urisys__cli__main --> src__urisys__cli__resolve_markpact_source
    src__urisys__cli__main --> src__urisys__doctor__run_doctor
    src__urisys__cli__main --> src__urisys__cli__print_json
    src__urisys__cli__main --> scripts__run_nl_log_smoke__print
    src__urisys__doctor___version_lt --> src__urisys__doctor___parse_version
    src__urisys__doctor___check_import --> src__urisys__doctor___pkg_version
    src__urisys__doctor___check_min_version --> src__urisys__doctor___pkg_version
    src__urisys__doctor___check_min_version --> src__urisys__doctor___version_lt
    src__urisys__doctor__run_doctor --> src__urisys__doctor___check_min_version
    src__urisys__doctor__run_doctor --> src__urisys__doctor___check_wayland_him
    src__urisys__doctor__run_doctor --> src__urisys__doctor___check_python
    src__urisys__doctor__run_doctor --> src__urisys__doctor___check_cli_path
    src__urisys__doctor__run_doctor --> src__urisys__doctor___check_import
    src__urisys__http_server__create_server --> src__urisys__http_server___send
    src__urisys__http_server__create_server --> src__urisys__http_server___read_json
    src__urisys__controllers__flow_controller__FlowController__run --> src__urisys__flow__load_flow
    src__urisys__controllers__flow_controller__FlowController__run --> src__urisys__flow__iter_steps
    src__urisys__controllers__server_controller__ServerController____init__ --> src__urisys__http_server__create_server
    src__urisys__controllers__server_controller__ServerController__serve_forever --> scripts__run_nl_log_smoke__print
    uristepper_docker__packages__python__uristepperedge__runtime__build_runtime --> uristepper_docker__packages__python__uristepperedge__runtime__load_json
    uristepper_docker__packages__python__uristepperedge__cli__cmd_call --> uristepper_docker__packages__python__uristepperedge__runtime__build_runtime
    uristepper_docker__packages__python__uristepperedge__cli__cmd_call --> uristepper_docker__packages__python__uristepperedge__cli___json_arg
    uristepper_docker__packages__python__uristepperedge__cli__cmd_call --> scripts__run_nl_log_smoke__print
    uristepper_docker__packages__python__uristepperedge__cli__cmd_explain --> uristepper_docker__packages__python__uristepperedge__runtime__build_runtime
    uristepper_docker__packages__python__uristepperedge__cli__cmd_explain --> scripts__run_nl_log_smoke__print
    uristepper_docker__packages__python__uristepperedge__cli__cmd_routes --> uristepper_docker__packages__python__uristepperedge__runtime__build_runtime
    uristepper_docker__packages__python__uristepperedge__cli__cmd_routes --> scripts__run_nl_log_smoke__print
    uristepper_docker__packages__python__uristepperedge__cli__cmd_events --> uristepper_docker__packages__python__uristepperedge__runtime__build_runtime
    uristepper_docker__packages__python__uristepperedge__cli__cmd_events --> scripts__run_nl_log_smoke__print
    uristepper_docker__packages__python__uristepperedge__cli__cmd_flow --> uristepper_docker__packages__python__uristepperedge__runtime__build_runtime
    uristepper_docker__packages__python__uristepperedge__cli__cmd_flow --> scripts__run_nl_log_smoke__print
    uristepper_docker__packages__python__uristepperedge__cli__cmd_serve --> packages__python__urisysedge__runtime__serve
    uristepper_docker__packages__python__uristepperedge__server__serve --> uristepper_docker__packages__python__uristepperedge__runtime__build_runtime
    uristepper_docker__packages__python__uristepperedge__server__serve --> scripts__run_nl_log_smoke__print
    uristepper_docker__packages__python__uristepperedge__server__serve --> uristepper_docker__packages__python__uristepperedge__server__make_handler
    uristepper_docker__packages__python__uristepper__handlers___driver --> uristepper_docker__packages__python__uristepper__drivers__make_driver
    uristepper_docker__packages__python__uristepper__handlers___dry_or_driver --> uristepper_docker__packages__python__uristepper__handlers___driver
    uristepper_docker__packages__python__uristepper__handlers__status --> uristepper_docker__packages__python__uristepper__handlers___device_axis
    uristepper_docker__packages__python__uristepper__handlers__status --> uristepper_docker__packages__python__uristepper__handlers___dry_or_driver
    uristepper_docker__packages__python__uristepper__handlers__enable --> uristepper_docker__packages__python__uristepper__handlers___device_axis
    uristepper_docker__packages__python__uristepper__handlers__enable --> uristepper_docker__packages__python__uristepper__handlers___dry_or_driver
    uristepper_docker__packages__python__uristepper__handlers__disable --> uristepper_docker__packages__python__uristepper__handlers___device_axis
    uristepper_docker__packages__python__uristepper__handlers__disable --> uristepper_docker__packages__python__uristepper__handlers___dry_or_driver
    uristepper_docker__packages__python__uristepper__handlers__stop --> uristepper_docker__packages__python__uristepper__handlers___device_axis
    uristepper_docker__packages__python__uristepper__handlers__stop --> uristepper_docker__packages__python__uristepper__handlers___dry_or_driver
    uristepper_docker__packages__python__uristepper__handlers__move_relative --> uristepper_docker__packages__python__uristepper__handlers___device_axis
    uristepper_docker__packages__python__uristepper__handlers__move_relative --> uristepper_docker__packages__python__uristepper__handlers___enforce_safety
    uristepper_docker__packages__python__uristepper__handlers__move_relative --> uristepper_docker__packages__python__uristepper__handlers___dry_or_driver
    uristepper_docker__packages__python__uristepper__handlers__move_absolute --> uristepper_docker__packages__python__uristepper__handlers___device_axis
    uristepper_docker__packages__python__uristepper__handlers__move_absolute --> uristepper_docker__packages__python__uristepper__handlers___enforce_safety
    uristepper_docker__packages__python__uristepper__handlers__move_absolute --> uristepper_docker__packages__python__uristepper__handlers___dry_or_driver
    uristepper_docker__packages__python__uristepper__handlers__home --> uristepper_docker__packages__python__uristepper__handlers___device_axis
    uristepper_docker__packages__python__uristepper__handlers__home --> uristepper_docker__packages__python__uristepper__handlers___dry_or_driver
    scripts__office_simulate_loop__rules_tick --> scripts__office_simulate_loop__call_uri
    scripts__office_simulate_loop__rules_tick --> scripts__run_nl_log_smoke__print
    scripts__office_simulate_loop__llm_tick --> scripts__office_simulate_loop__call_uri
    scripts__office_simulate_loop__llm_tick --> scripts__run_nl_log_smoke__print
    scripts__office_simulate_loop__main --> scripts__office_simulate_loop__parse_args
    scripts__office_simulate_loop__main --> scripts__run_nl_log_smoke__print
    scripts__office_simulate_loop__main --> scripts__office_simulate_loop__rules_tick
    scripts__office_simulate_loop__main --> scripts__office_simulate_loop__llm_tick
    scripts__report__cli__main --> scripts__report__run_analysis__analyze_run
    scripts__report__cli__main --> scripts__report__run_analysis__write_run_analysis
    scripts__report__events__summarize_events --> scripts__report__events__load_event_records
    scripts__report__events__summarize_events --> scripts__report__events__summarize_event_records
    scripts__report__events__merge_event_summaries --> scripts__report__events__summarize_events
    scripts__report__run_analysis__analyze_run --> scripts__report__util__read_json
    scripts__report__run_analysis__write_run_analysis --> scripts__report__run_analysis__analyze_run
    scripts__report__run_analysis__write_run_analysis --> scripts__report__run_markdown__render_run_analysis_markdown
    scripts__report__lab_checks__load_flow_outcomes --> scripts__report__util__read_json
    scripts__report__lab_checks__load_flow_outcomes --> scripts__report__lab_checks__iter_step_results
    scripts__report__lab_checks__check_duplicate_screenshots --> scripts__report__lab_checks___duplicate_recommendation
    scripts__report__lab_checks__analyze_lab_flows --> scripts__report__lab_checks__load_flow_outcomes
    scripts__report__session__infer_steps --> scripts__report__util__read_json
    scripts__report__session__session_duration --> scripts__report__util__now_iso
    scripts__report__session__generate_report --> scripts__report__session__infer_steps
    scripts__report__session__generate_report --> scripts__report__util__read_json
    scripts__report__session__generate_report --> packages__python__urisysedge__runtime__JsonlEventStore__tail
    scripts__report__session_markdown__render_session_markdown --> scripts__report__session_markdown___environment_section
    scripts__report__session_markdown__render_session_markdown --> scripts__report__session_markdown___steps_section
    scripts__report__session_markdown__render_session_markdown --> scripts__report__session_markdown___screenshots_section
    scripts__report__session_io__write_session_report --> scripts__report__session__generate_report
    scripts__report__session_io__write_session_report --> scripts__report__session_markdown__render_session_markdown
    scripts__test_sessions__expectations___ocr_contains --> scripts__test_sessions__expectations__ocr_texts
    scripts__test_sessions__expectations___min_vision_confidence --> scripts__test_sessions__expectations__vision_confidences
    scripts__test_sessions__expectations__evaluate_expectations --> scripts__test_sessions__expectations___screen_changed
    scripts__test_sessions__expectations__evaluate_expectations --> scripts__test_sessions__expectations___screen_changed_since_previous
    scripts__test_sessions__expectations__evaluate_expectations --> scripts__test_sessions__expectations___opened_url_contains
    scripts__test_sessions__expectations__evaluate_expectations --> scripts__test_sessions__expectations___ocr_contains
    scripts__test_sessions__expectations__evaluate_expectations --> scripts__test_sessions__expectations___min_vision_confidence
    scripts__test_sessions__lab_flows___lab_bootstrap --> scripts__test_sessions__util__run_cmd
    scripts__test_sessions__lab_flows___lab_bootstrap --> scripts__test_sessions__util__write_meta
    scripts__test_sessions__lab_flows___capture_flow_screenshot --> scripts__test_sessions__lab_rdp__capture_rdp_screenshot_wait
    scripts__test_sessions__lab_flows___capture_flow_screenshot --> scripts__test_sessions__lab_rdp__capture_rdp_screenshot
    scripts__test_sessions__lab_flows___capture_flow_screenshot --> scripts__test_sessions__util__file_md5
    scripts__test_sessions__lab_flows___run_single_lab_flow --> scripts__test_sessions__expectations__flow_expectations
    scripts__test_sessions__lab_flows___run_single_lab_flow --> scripts__test_sessions__lab_flows___capture_flow_screenshot
    scripts__test_sessions__lab_flows___run_single_lab_flow --> scripts__test_sessions__expectations__evaluate_expectations
    scripts__test_sessions__lab_flows___run_single_lab_flow --> scripts__run_office_simulate_lenovo__save_json
    scripts__test_sessions__lab_flows___run_single_lab_flow --> scripts__run_urisys_node_docker_e2e__http_json
    scripts__test_sessions__lab_flows___run_single_lab_flow --> scripts__test_sessions__lab_flows___flow_step_detail
    scripts__test_sessions__lab_flows__session_lab_10_flows --> scripts__report__util__now_iso
    scripts__test_sessions__lab_flows__session_lab_10_flows --> scripts__test_sessions__util__write_meta
    scripts__test_sessions__lab_flows__session_lab_10_flows --> scripts__test_sessions__util__sleep_ports
    scripts__test_sessions__lab_flows__session_lab_10_flows --> scripts__test_sessions__util__run_cmd
    scripts__test_sessions__lab_flows__session_lab_10_flows --> scripts__test_sessions__util__finalize_session
    scripts__test_sessions__lab_flows__session_lab_10_flows --> scripts__run_office_simulate_e2e__wait_health
    scripts__test_sessions__lab_rdp__prepare_ok_target --> scripts__run_urisys_node_docker_e2e__http_json
    scripts__test_sessions__lab_rdp__capture_rdp_screenshot --> scripts__run_urisys_node_docker_e2e__http_json
    scripts__test_sessions__lab_rdp__capture_rdp_screenshot --> scripts__test_sessions__util__copy_container_file
    scripts__test_sessions__lab_rdp__capture_rdp_screenshot_wait --> scripts__test_sessions__lab_rdp__capture_rdp_screenshot
    scripts__test_sessions__lab_rdp__capture_rdp_screenshot_wait --> scripts__test_sessions__util__file_md5
    scripts__test_sessions__util__wait_health --> scripts__test_sessions__util__http_json
    scripts__test_sessions__util__write_meta --> scripts__test_sessions__util__read_meta
    scripts__test_sessions__util__write_meta --> scripts__test_sessions__util__save_json
    scripts__test_sessions__util__finalize_session --> scripts__test_sessions__util__now_iso
    scripts__test_sessions__util__finalize_session --> scripts__test_sessions__util__write_meta
    scripts__test_sessions__util__docker_logs --> scripts__test_sessions__util__compose_cmd
    scripts__test_sessions__util__docker_logs --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdpedge__cli__build_runtime --> packages__python__urisysedge__runtime__load_json
    urirdp_docker__packages__python__urirdp_ocr__handlers___tesseract_ocr --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp_ocr__handlers___tesseract_ocr --> urirdp_docker__packages__python__urirdp_ocr__handlers___parse_tesseract_tsv
    urirdp_docker__packages__python__urirdp_ocr__handlers__latest_text --> urirdp_docker__packages__python__urirdp_ocr__handlers__image_text
    urirdp_docker__packages__python__urirdp_ocr__handlers__image_text --> urirdp_docker__packages__python__urirdp_ocr__handlers___tesseract_ocr
    urirdp_docker__packages__python__urirdp_ocr__handlers__image_text --> urirdp_docker__packages__python__urirdp_ocr__handlers___mock_ocr
    urirdp_docker__packages__python__urirdp_ocr__handlers__image_text --> urirdp_docker__packages__python__urirdp_kvm__display__allow_real
    urirdp_docker__packages__python__urirdp_shell__handlers___mock --> urirdp_docker__packages__python__urirdp_shell__handlers___detect_display
    urirdp_docker__packages__python__urirdp_shell__handlers__shell_run --> urirdp_docker__packages__python__urirdp_shell__handlers___detect_display
    urirdp_docker__packages__python__urirdp_shell__handlers__shell_run --> urirdp_docker__packages__python__urirdp_shell__handlers___mock
    urirdp_docker__packages__python__urirdp_him__handlers___mock --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp_him__handlers__mouse_move --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp_him__handlers__mouse_move --> urirdp_docker__packages__python__urirdp_him__handlers___mock
    urirdp_docker__packages__python__urirdp_him__handlers__mouse_move --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp_him__handlers__mouse_move --> urirdp_docker__packages__python__urirdp_kvm__display__allow_real
    urirdp_docker__packages__python__urirdp_him__handlers__mouse_click --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp_him__handlers__mouse_click --> urirdp_docker__packages__python__urirdp_him__handlers___mock
    urirdp_docker__packages__python__urirdp_him__handlers__mouse_click --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_type --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_type --> urirdp_docker__packages__python__urirdp_him__handlers___mock
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_type --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_key --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_key --> urirdp_docker__packages__python__urirdp_him__handlers___mock
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_key --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_key --> urirdp_docker__packages__python__urirdp_kvm__display__allow_real
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_type_text --> urirdp_docker__packages__python__urirdp_him__handlers__keyboard_type
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_hotkey --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_hotkey --> urirdp_docker__packages__python__urirdp_him__handlers___mock
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_hotkey --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp_him__handlers__keyboard_hotkey --> urirdp_docker__packages__python__urirdp_kvm__display__allow_real
    urirdp_docker__packages__python__urirdp__handlers__status --> urirdp_docker__packages__python__urirdp__handlers___service_status
    urirdp_docker__packages__python__urirdp__handlers__status --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp__handlers__display --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp__handlers__display --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp__handlers__display_status --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp__handlers__display_status --> urirdp_docker__packages__python__urirdp_kvm__display__allow_real
    urirdp_docker__packages__python__urirdp__handlers__display_status --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp__handlers___dismiss_stale_targets --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp__handlers___dismiss_stale_targets --> urirdp_docker__packages__python__urirdp_kvm__display__allow_real
    urirdp_docker__packages__python__urirdp__handlers__dismiss_target --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp__handlers__dismiss_target --> urirdp_docker__packages__python__urirdp__handlers___dismiss_stale_targets
    urirdp_docker__packages__python__urirdp__handlers__dismiss_target --> urirdp_docker__packages__python__urirdp_kvm__display__allow_real
    urirdp_docker__packages__python__urirdp__handlers__prepare_target --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp__handlers__prepare_target --> urirdp_docker__packages__python__urirdp__handlers___dismiss_stale_targets
    urirdp_docker__packages__python__urirdp__handlers__prepare_target --> urirdp_docker__packages__python__urirdp_kvm__display__base_env
    urirdp_docker__packages__python__urirdp__handlers__prepare_target --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp_browser__handlers__open_page --> urirdp_docker__packages__python__urirdp_browser__handlers___profile
    urirdp_docker__packages__python__urirdp_browser__handlers__open_page --> urirdp_docker__packages__python__urirdp_browser__handlers___session_state
    urirdp_docker__packages__python__urirdp_browser__handlers__open_page --> urirdp_docker__packages__python__urirdp_browser__handlers___chromium_binary
    urirdp_docker__packages__python__urirdp_browser__handlers__open_page --> urirdp_docker__packages__python__urirdp__handlers___dismiss_stale_targets
    urirdp_docker__packages__python__urirdp_kvm__display__detect_display --> urirdp_docker__packages__python__urirdp_kvm__display__config_value
    urirdp_docker__packages__python__urirdp_kvm__display__base_env --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp_kvm__display__base_env --> urirdp_docker__packages__python__urirdp_kvm__display__config_value
    urirdp_docker__packages__python__urirdp_kvm__display__run_cmd --> urirdp_docker__packages__python__urirdp_kvm__display__base_env
    urirdp_docker__packages__python__urirdp_kvm__display__ensure_screenshot_dir --> urirdp_docker__packages__python__urirdp_kvm__display__config_value
    urirdp_docker__packages__python__urirdp_kvm__handlers__display_info --> urirdp_docker__packages__python__urirdp_kvm__display__detect_display
    urirdp_docker__packages__python__urirdp_kvm__handlers__display_info --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp_kvm__handlers__screenshot --> urirdp_docker__packages__python__urirdp_kvm__display__ensure_screenshot_dir
    urirdp_docker__packages__python__urirdp_kvm__handlers__screenshot --> scripts__test_sessions__util__run_cmd
    urirdp_docker__packages__python__urirdp_llm__handlers___llm_cfg --> urirdp_docker__packages__python__urirdp_llm__handlers___config
    urirdp_docker__packages__python__urirdp_llm__handlers___env --> packages__python__urisysedge__env__resolve_env_var
    urirdp_docker__packages__python__urirdp_llm__handlers___env --> packages__python__urisysedge__env__is_secret_env
    urirdp_docker__packages__python__urirdp_llm__handlers___screenshot_b64 --> urirdp_docker__packages__python__urirdp_llm__handlers___config
    urirdp_docker__packages__python__urirdp_llm__handlers___openai_compatible_chat --> urirdp_docker__packages__python__urirdp_llm__handlers___parse_json_response
    urirdp_docker__packages__python__urirdp_llm__handlers___litellm_chat --> urirdp_docker__packages__python__urirdp_llm__handlers___parse_json_response
    urirdp_docker__packages__python__urirdp_llm__handlers__analyze --> urirdp_docker__packages__python__urirdp_llm__handlers___llm_cfg
    urirdp_docker__packages__python__urirdp_llm__handlers__analyze --> urirdp_docker__packages__python__urirdp_llm__handlers___target
    urirdp_docker__packages__python__urirdp_llm__handlers__analyze --> urirdp_docker__packages__python__urirdp_llm__handlers___env
    urirdp_docker__packages__python__urirdp_llm__handlers__analyze --> urirdp_docker__packages__python__urirdp_llm__handlers___screenshot_b64
    urirdp_docker__packages__python__urirdp_llm__handlers__analyze --> urirdp_docker__packages__python__urirdp_llm__handlers___vision_messages
    urirdp_docker__packages__python__urirdp_llm__handlers__analyze --> urirdp_docker__packages__python__urirdp_llm__handlers___heuristic
    urirdp_docker__packages__python__urirdp_llm__handlers___decide_litellm --> packages__python__urisysedge__env__resolve_env_var
    urirdp_docker__packages__python__urirdp_llm__handlers___decide_litellm --> urirdp_docker__packages__python__urirdp_llm__handlers___litellm_chat
    urirdp_docker__packages__python__urirdp_llm__handlers___decide_openai --> urirdp_docker__packages__python__urirdp_llm__handlers___openai_compatible_chat
    urirdp_docker__packages__python__urirdp_llm__handlers___decide_openai --> packages__python__urisysedge__env__resolve_env_var
    urirdp_docker__packages__python__urirdp_llm__handlers__decide --> urirdp_docker__packages__python__urirdp_llm__handlers___llm_cfg
    urirdp_docker__packages__python__urirdp_llm__handlers__decide --> urirdp_docker__packages__python__urirdp_llm__handlers___env
    urirdp_docker__packages__python__urirdp_llm__handlers__decide --> urirdp_docker__packages__python__urirdp_llm__handlers___decide_messages
    urirdp_docker__packages__python__urirdp_llm__handlers__plan --> urirdp_docker__packages__python__urirdp_llm__handlers___llm_cfg
    urirdp_docker__packages__python__urirdp_llm__handlers__plan --> urirdp_docker__packages__python__urirdp_llm__handlers___match_transcript
    urirdp_docker__packages__python__urirdp_llm__handlers__plan --> urirdp_docker__packages__python__urirdp_kvm__display__allow_real
    urirdp_docker__packages__python__urirdp_llm__handlers__plan --> urirdp_docker__packages__python__urirdp_llm__handlers___env
    uribrowser_docker__packages__python__uribrowseredge__cli__build_runtime --> packages__python__urisysedge__runtime__load_json
    urikvm_docker__packages__python__urikvm__handlers__monitor_list --> urikvm_docker__packages__python__urikvm__handlers___profile
    urikvm_docker__packages__python__urikvm__handlers__screenshot --> urikvm_docker__packages__python__urikvm__handlers___store_screenshot
    urikvm_docker__packages__python__urikvm__handlers__screenshot --> urikvm_docker__packages__python__urikvm__handlers___profile
    urikvm_docker__packages__python__urikvmedge__cli__build_runtime --> packages__python__urisysedge__runtime__load_json
    urikvm_docker__packages__python__uriocr__handlers___driver --> urikvm_docker__packages__python__uriocr__handlers___ocr_cfg
    urikvm_docker__packages__python__uriocr__handlers___mock_boxes --> urikvm_docker__packages__python__uriocr__handlers___ocr_cfg
    urikvm_docker__packages__python__uriocr__handlers___png_bytes --> urikvm_docker__packages__python__uriocr__handlers___latest_screenshot
    urikvm_docker__packages__python__uriocr__handlers___extract_text --> urikvm_docker__packages__python__uriocr__handlers___driver
    urikvm_docker__packages__python__uriocr__handlers___extract_text --> urikvm_docker__packages__python__uriocr__handlers___mock_boxes
    urikvm_docker__packages__python__uriocr__handlers___extract_text --> urikvm_docker__packages__python__uriocr__handlers___png_bytes
    urikvm_docker__packages__python__uriocr__handlers___extract_text --> urikvm_docker__packages__python__uriocr__handlers___merge_word_boxes
    urikvm_docker__packages__python__uriocr__handlers___extract_text --> urikvm_docker__packages__python__uriocr__handlers___tesseract_boxes
    urikvm_docker__packages__python__uriocr__handlers___extract_text --> urikvm_docker__packages__python__uriocr__handlers___ocr_cfg
    urikvm_docker__packages__python__uriocr__handlers__latest_text --> urikvm_docker__packages__python__uriocr__handlers___extract_text
    urikvm_docker__packages__python__uriocr__handlers__image_text --> urikvm_docker__packages__python__uriocr__handlers___extract_text
    urikvm_docker__packages__python__urihim__handlers___driver --> urikvm_docker__packages__python__urihim__handlers___xdotool_available
    urikvm_docker__packages__python__urihim__handlers___driver --> urikvm_docker__packages__python__urihim__handlers___real_allowed
    urikvm_docker__packages__python__urihim__handlers___driver --> urikvm_docker__packages__python__urihim__handlers___wayland_session
    urikvm_docker__packages__python__urihim__handlers___driver --> urikvm_docker__packages__python__urihim__handlers___ydotool_available
    urikvm_docker__packages__python__urihim__handlers___pyautogui --> urikvm_docker__packages__python__urihim__handlers___real_allowed
    urikvm_docker__packages__python__urihim__handlers___run_ydotool --> urikvm_docker__packages__python__urihim__handlers___real_allowed
    urikvm_docker__packages__python__urihim__handlers___run_ydotool --> urikvm_docker__packages__python__urihim__handlers___ydotool_available
    urikvm_docker__packages__python__urihim__handlers___run_xdotool --> urikvm_docker__packages__python__urihim__handlers___real_allowed
    urikvm_docker__packages__python__urihim__handlers___run_xdotool --> urikvm_docker__packages__python__urihim__handlers___xdotool_available
    urikvm_docker__packages__python__urihim__handlers__mouse_status --> urikvm_docker__packages__python__urihim__handlers___state
    urikvm_docker__packages__python__urihim__handlers__mouse_status --> urikvm_docker__packages__python__urihim__handlers___driver
    urikvm_docker__packages__python__urihim__handlers__mouse_move --> urikvm_docker__packages__python__urihim__handlers___driver
    urikvm_docker__packages__python__urihim__handlers__mouse_move --> urikvm_docker__packages__python__urihim__handlers___state
    urikvm_docker__packages__python__urihim__handlers__mouse_click --> urikvm_docker__packages__python__urihim__handlers___driver
    urikvm_docker__packages__python__urihim__handlers__mouse_click --> urikvm_docker__packages__python__urihim__handlers___state
    urikvm_docker__packages__python__urihim__handlers__mouse_click --> urikvm_docker__packages__python__urihim__handlers___pyautogui
    urikvm_docker__packages__python__urihim__handlers__keyboard_type --> urikvm_docker__packages__python__urihim__handlers___driver
    urikvm_docker__packages__python__urihim__handlers__keyboard_type --> urikvm_docker__packages__python__urihim__handlers___run_ydotool
    urikvm_docker__packages__python__urihim__handlers__keyboard_type --> urikvm_docker__packages__python__urihim__handlers___pyautogui
    urikvm_docker__packages__python__urihim__handlers__mouse_scroll --> urikvm_docker__packages__python__urihim__handlers___driver
    urikvm_docker__packages__python__urihim__handlers__mouse_scroll --> urikvm_docker__packages__python__urihim__handlers___state
    urikvm_docker__packages__python__urihim__handlers__mouse_scroll --> urikvm_docker__packages__python__urihim__handlers___pyautogui
    urikvm_docker__packages__python__urihim__handlers__keyboard_hotkey --> urikvm_docker__packages__python__urihim__handlers___driver
    urikvm_docker__packages__python__urihim__handlers__keyboard_hotkey --> urikvm_docker__packages__python__urihim__handlers___ydotool_key_sequence
    urikvm_docker__packages__python__urihim__handlers__keyboard_hotkey --> urikvm_docker__packages__python__urihim__handlers___run_ydotool
    urikvm_docker__scripts__real_pipeline__build_runtime --> packages__python__urisysedge__runtime__load_json
    urikvm_docker__scripts__real_pipeline__main --> urikvm_docker__scripts__real_pipeline__build_runtime
    urikvm_docker__scripts__real_pipeline__main --> scripts__run_nl_log_smoke__print
    urisys_automation_lab__packages__python__uriwebrtc__handlers__session_start --> urisys_automation_lab__packages__python__uriwebrtc__handlers___room_id
    urisys_automation_lab__packages__python__uriwebrtc__handlers__data_send --> urisys_automation_lab__packages__python__uriwebrtc__handlers___room_id
    urisys_automation_lab__packages__python__urichat__handlers__uri_execute --> urisys_automation_lab__packages__python__urichat__handlers___forward_uri
    urisys_automation_lab__packages__python__uristt__handlers__session_start --> urisys_automation_lab__packages__python__uristt__handlers___session_id
    urisys_automation_lab__packages__python__uristt__handlers__session_transcript --> urisys_automation_lab__packages__python__uristt__handlers___session_id
    urisys_automation_lab__web__app__uriCall --> urisys_automation_lab__web__app__log
    urisys_automation_lab__web__app__data --> urisys_automation_lab__web__app__log
    urisys_automation_lab__web__app__SR --> urisys_automation_lab__web__app__log
    urisys_automation_lab__web__app__rec --> urisys_automation_lab__web__app__log
    urisys_automation_lab__web__app__text --> urisys_automation_lab__web__app__uriCall
    urisys_automation_lab__server__flow_runner__plan_flow --> urisys_automation_lab__server__flow_runner___require_uri_stack
    urisys_automation_lab__server__flow_runner__plan_flow --> urisys_automation_lab__server__flow_runner___load_defaults
    urisys_automation_lab__server__flow_runner__run_flow_file --> urisys_automation_lab__server__flow_runner___require_uri_stack
    urisys_automation_lab__server__flow_runner__run_flow_file --> urisys_automation_lab__server__flow_runner__plan_flow
    urisys_automation_lab__server__flow_runner__run_flow_file --> urisys_automation_lab__server__flow_runner___lab_adapter_session
    urisys_automation_lab__server__automation_lab_server__build_lab_runtime --> packages__python__urisysedge__runtime__load_json
    urisys_automation_lab__server__automation_lab_server__LabHandler__log_message --> scripts__run_nl_log_smoke__print
    urisys_automation_lab__server__automation_lab_server__serve --> urisys_automation_lab__server__automation_lab_server__build_lab_runtime
    urisys_automation_lab__server__automation_lab_server__serve --> scripts__run_nl_log_smoke__print
    urisys_automation_lab__server__lab_uri_adapter__LabCallAdapter__execute --> urisys_automation_lab__server__lab_uri_adapter__step_ok
    urienv_docker__packages__python__urienv__src__urienv__handlers___cfg --> urienv_docker__packages__python__urienv__src__urienv__handlers___split_csv
    urienv_docker__packages__python__urienv__src__urienv__handlers___get_value --> urienv_docker__packages__python__urienv__src__urienv__handlers___read_docker_secret
    urienv_docker__packages__python__urienv__src__urienv__handlers___require_visible --> urienv_docker__packages__python__urienv__src__urienv__handlers___is_secret
    urienv_docker__packages__python__urienv__src__urienv__handlers___require_visible --> urienv_docker__packages__python__urienv__src__urienv__handlers___is_public
    urienv_docker__packages__python__urienv__src__urienv__handlers__health --> urienv_docker__packages__python__urienv__src__urienv__handlers___cfg
    urienv_docker__packages__python__urienv__src__urienv__handlers__list_vars --> urienv_docker__packages__python__urienv__src__urienv__handlers___cfg
    urienv_docker__packages__python__urienv__src__urienv__handlers__list_vars --> urienv_docker__packages__python__urienv__src__urienv__handlers___get_value
    urienv_docker__packages__python__urienv__src__urienv__handlers__list_vars --> urienv_docker__packages__python__urienv__src__urienv__handlers___mask
    urienv_docker__packages__python__urienv__src__urienv__handlers__startup_config --> urienv_docker__packages__python__urienv__src__urienv__handlers___cfg
    urienv_docker__packages__python__urienv__src__urienv__handlers__startup_config --> urienv_docker__packages__python__urienv__src__urienv__handlers___get_value
    urienv_docker__packages__python__urienv__src__urienv__handlers__startup_config --> urienv_docker__packages__python__urienv__src__urienv__handlers___mask
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_exists --> urienv_docker__packages__python__urienv__src__urienv__handlers___cfg
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_exists --> urienv_docker__packages__python__urienv__src__urienv__handlers___name
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_exists --> urienv_docker__packages__python__urienv__src__urienv__handlers___get_value
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_value --> urienv_docker__packages__python__urienv__src__urienv__handlers___cfg
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_value --> urienv_docker__packages__python__urienv__src__urienv__handlers___name
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_value --> urienv_docker__packages__python__urienv__src__urienv__handlers___require_visible
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_value --> urienv_docker__packages__python__urienv__src__urienv__handlers___get_value
    urienv_docker__packages__python__urienv__src__urienv__handlers__secret_masked --> urienv_docker__packages__python__urienv__src__urienv__handlers___cfg
    urienv_docker__packages__python__urienv__src__urienv__handlers__secret_masked --> urienv_docker__packages__python__urienv__src__urienv__handlers___name
    urienv_docker__packages__python__urienv__src__urienv__handlers__secret_masked --> urienv_docker__packages__python__urienv__src__urienv__handlers___get_value
    urienv_docker__packages__python__urienv__src__urienv__handlers__secret_masked --> urienv_docker__packages__python__urienv__src__urienv__handlers___is_secret
    urienv_docker__packages__python__urienv__src__urienv__handlers__secret_masked --> urienv_docker__packages__python__urienv__src__urienv__handlers___mask
    urienv_docker__packages__python__urienv__src__urienv__handlers__secret_value --> urienv_docker__packages__python__urienv__src__urienv__handlers___cfg
    urienv_docker__packages__python__urienv__src__urienv__handlers__secret_value --> urienv_docker__packages__python__urienv__src__urienv__handlers___name
    urienv_docker__packages__python__urienv__src__urienv__handlers__secret_value --> urienv_docker__packages__python__urienv__src__urienv__handlers___get_value
    urienv_docker__packages__python__urienv__src__urienv__handlers__secret_value --> urienv_docker__packages__python__urienv__src__urienv__handlers___is_secret
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_set --> urienv_docker__packages__python__urienv__src__urienv__handlers___cfg
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_set --> urienv_docker__packages__python__urienv__src__urienv__handlers___name
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_set --> urienv_docker__packages__python__urienv__src__urienv__handlers___is_mutable
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_unset --> urienv_docker__packages__python__urienv__src__urienv__handlers___cfg
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_unset --> urienv_docker__packages__python__urienv__src__urienv__handlers___name
    urienv_docker__packages__python__urienv__src__urienv__handlers__var_unset --> urienv_docker__packages__python__urienv__src__urienv__handlers___is_mutable
    urienv_docker__packages__python__urisysedge__src__urisysedge__runtime__build_runtime --> src__urisys__managers__pack_manager__PackManager__manifest_paths
    urienv_docker__packages__python__urisysedge__src__urisysedge__pack_loader__manifest_paths --> urienv_docker__packages__python__urisysedge__src__urisysedge__pack_loader__manifest_path_for_pack
    urienv_docker__packages__python__urisysedge__src__urisysedge__server__serve --> uristepper_docker__packages__python__uristepperedge__runtime__build_runtime
    urienv_docker__packages__python__urisysedge__src__urisysedge__server__serve --> urienv_docker__packages__python__urisysedge__src__urisysedge__runtime__load_device_config
    urienv_docker__packages__python__urisysedge__src__urisysedge__server__serve --> urienv_docker__packages__python__urisysedge__src__urisysedge__runtime__load_env_config
    urienv_docker__packages__python__urisysedge__src__urisysedge__server__serve --> scripts__run_nl_log_smoke__print
    urienv_docker__packages__python__urisysedge__src__urisysedge__flow__run_flow --> urienv_docker__packages__python__urisysedge__src__urisysedge__runtime__result_to_dict
    urisys_node__packages__python__uriscreen__handlers___backend --> urisys_node__packages__python__uriscreen__handlers___screen_cfg
    urisys_node__packages__python__uriscreen__handlers___output_dir --> urisys_node__packages__python__uriscreen__handlers___screen_cfg
    urisys_node__packages__python__uriscreen__handlers___monitor_index --> urisys_node__packages__python__uriscreen__handlers___screen_cfg
    urisys_node__packages__python__uriscreen__handlers__capture --> urisys_node__packages__python__uriscreen__handlers___monitor_index
    urisys_node__packages__python__uriscreen__handlers__capture --> urisys_node__packages__python__uriscreen__handlers___output_dir
    urisys_node__packages__python__uriscreen__handlers__capture --> urisys_node__packages__python__uriscreen__backends__resolve_backend
    urisys_node__packages__python__uriscreen__handlers__capture --> urisys_node__packages__python__uriscreen__backends__capture_with_fallback
    urisys_node__packages__python__uriscreen__handlers__capture --> urisys_node__packages__python__uriscreen__handlers___store_latest
    urisys_node__packages__python__uriscreen__handlers__frame --> urisys_node__packages__python__uriscreen__handlers__capture
    urisys_node__packages__python__uriscreen__handlers__capture_loop --> urisys_node__packages__python__uriscreen__backends__resolve_backend
    urisys_node__packages__python__uriscreen__handlers__capture_loop --> urisys_node__packages__python__uriscreen__handlers__capture
    urisys_node__packages__python__uriscreen__backends__is_wayland --> urisys_node__packages__python__uriscreen__backends__session_type
    urisys_node__packages__python__uriscreen__backends__vdisplay_agent_up --> urisys_node__packages__python__uriscreen__backends___http_json
    urisys_node__packages__python__uriscreen__backends__vdisplay_agent_up --> urisys_node__packages__python__uriscreen__backends__vdisplay_agent_url
    urisys_node__packages__python__uriscreen__backends__vdisplay_screencast_ready --> urisys_node__packages__python__uriscreen__backends___http_json
    urisys_node__packages__python__uriscreen__backends__vdisplay_screencast_ready --> urisys_node__packages__python__uriscreen__backends__vdisplay_agent_url
    urisys_node__packages__python__uriscreen__backends__resolve_backend --> urisys_node__packages__python__uriscreen__backends__is_wayland
    urisys_node__packages__python__uriscreen__backends__resolve_backend --> urisys_node__packages__python__uriscreen__backends__vdisplay_agent_up
    urisys_node__packages__python__uriscreen__backends__resolve_backend --> urisys_node__packages__python__uriscreen__backends__vdisplay_screencast_ready
    urisys_node__packages__python__uriscreen__backends__capture_vdisplay --> urisys_node__packages__python__uriscreen__backends___http_json
    urisys_node__packages__python__uriscreen__backends__capture_portal --> urisys_node__packages__python__uriscreen__portal_capture__capture_portal_png
    urisys_node__packages__python__uriscreen__backends__capture_with_fallback --> urisys_node__packages__python__uriscreen__backends__resolve_backend
    urisys_node__packages__python__uriscreen__backends__capture_with_fallback --> urisys_node__packages__python__uriscreen__backends__is_wayland
    urisys_node__packages__python__uriscreen__backends__capture_with_fallback --> urisys_node__packages__python__uriscreen__backends__capture_vdisplay
    urisys_node__packages__python__uriscreen__backends__capture_with_fallback --> urisys_node__packages__python__uriscreen__backends__is_black_png
    urisys_node__packages__python__uriscreen__portal_capture__capture_portal_png --> urisys_node__packages__python__uriscreen__portal_capture___portal_python
    urisys_node__packages__python__urisysnode__release_verify__verify_release --> urisys_node__packages__python__urisysnode__release_verify__signature_required
    urisys_node__packages__python__urisysnode__release_verify__verify_release --> urisys_node__packages__python__urisysnode__release_verify__canonical_digest
    urisys_node__packages__python__urisysnode__release_verify__verify_release --> urisys_node__packages__python__urisysnode__release_verify___ed25519_verify
    urisys_node__packages__python__urisysnode__forward_config__load_forward_entries --> urisys_node__packages__python__urisysnode__forward_config___normalize_entry
    urisys_node__packages__python__urisysnode__forward_config__wire_forward_packs --> urisys_node__packages__python__urisysnode__serve__register_forward_pack
    urisys_node__packages__python__urisysnode__forward_config__load_release_forward_entries --> urisys_node__packages__python__urisysnode__forward_config___normalize_release_entry
    urisys_node__packages__python__urisysnode__forward_config__wire_release_forward_packs --> urisys_node__packages__python__urisysnode__serve__hotload_release_pack
    urisys_node__packages__python__urisysnode__serve___register_pack --> urisys_node__packages__python__urisysnode__pack_resolver__auto_install_enabled
    urisys_node__packages__python__urisysnode__serve___register_pack --> urisys_node__packages__python__urisysnode__pack_resolver__ensure_pack_pypi
    urisys_node__packages__python__urisysnode__serve__build_runtime --> urisys_node__packages__python__urisysnode__serve___extend_pack_paths
    urisys_node__packages__python__urisysnode__serve__build_runtime --> packages__python__urisysedge__env__load_urisys_env
    urisys_node__packages__python__urisysnode__serve__build_runtime --> packages__python__urisysedge__runtime__load_json
    urisys_node__packages__python__urisysnode__serve__build_runtime --> urisys_node__packages__python__urisysnode__serve___register_pack
    urisys_node__packages__python__urisysnode__serve__ensure_pack_for_uri --> urisys_node__packages__python__urisysnode__pack_resolver__scheme_for_uri
    urisys_node__packages__python__urisysnode__serve__ensure_pack_for_uri --> urisys_node__packages__python__urisysnode__pack_resolver__pack_for_scheme
    urisys_node__packages__python__urisysnode__serve__ensure_pack_for_uri --> urisys_node__packages__python__urisysnode__serve__load_pack_into_runtime
    urisys_node__packages__python__urisysnode__serve__ensure_pack_for_uri --> urisys_node__packages__python__urisysnode__pack_resolver__pack_importable
    urisys_node__packages__python__urisysnode__serve__call_uri --> urisys_node__packages__python__urisysnode__pack_resolver__auto_install_enabled
    urisys_node__packages__python__urisysnode__serve__call_uri --> urisys_node__packages__python__urisysnode__serve__ensure_pack_for_uri
    urisys_node__packages__python__urisysnode__serve__call_uri --> urisys_node__packages__python__urisysnode__pack_resolver__scheme_for_uri
    urisys_node__packages__python__urisysnode__serve___release_forward_spec --> urisys_node__packages__python__urisysnode__artifact_resolver__contract_spec_from_release
    urisys_node__packages__python__urisysnode__serve__hotload_release_pack --> urisys_node__packages__python__urisysnode__release_verify__verify_release
    urisys_node__packages__python__urisysnode__serve__hotload_release_pack --> urisys_node__packages__python__urisysnode__serve__register_forward_pack
    urisys_node__packages__python__urisysnode__serve__hotload_release_pack --> urisys_node__packages__python__urisysnode__identity__require_paired
    urisys_node__packages__python__urisysnode__serve__hotload_release_pack --> urisys_node__packages__python__urisysnode__artifact_resolver__fetch_release
    urisys_node__packages__python__urisysnode__serve__hotload_release_pack --> urisys_node__packages__python__urisysnode__serve___release_forward_spec
    urisys_node__packages__python__urisysnode__serve__hotload_release_pack --> urisys_node__packages__python__urisysnode__artifact_resolver__run_release
    urisys_node__packages__python__urisysnode__serve__serve --> urisys_node__packages__python__urisysnode__identity__load_identity
    urisys_node__packages__python__urisysnode__serve__serve --> scripts__run_nl_log_smoke__print
    urisys_node__packages__python__urisysnode__serve__serve --> urisys_node__packages__python__urisysnode__display_bootstrap__bootstrap_wayland_capture
    urisys_node__packages__python__urisysnode__serve__serve --> urisys_node__packages__python__urisysnode__serve__make_handler
    urisys_node__packages__python__urisysnode__client__call_via_route_map --> urisys_node__packages__python__urisysnode__router__load_route_map
    urisys_node__packages__python__urisysnode__client__call_via_route_map --> urisys_node__packages__python__urisysnode__router__resolve_remote_route
    urisys_node__packages__python__urisysnode__client__call_via_route_map --> urisys_node__packages__python__urisysnode__router__node_endpoint
    urisys_node__packages__python__urisysnode__client__call_via_route_map --> urisys_node__packages__python__urisysnode__router__rewrite_uri_for_slave
    urisys_node__packages__python__urisysnode__client__call_via_route_map --> urisys_node__packages__python__urisysnode__client__remote_call
    urisys_node__packages__python__urisysnode__forward__forward_call --> scripts__run_urisys_node_docker_e2e__remote_call
    urisys_node__packages__python__urisysnode__handlers__query_health --> urisys_node__packages__python__urisysnode__identity__health_payload
    urisys_node__packages__python__urisysnode__handlers__query_identity --> urisys_node__packages__python__urisysnode__identity__load_identity
    urisys_node__packages__python__urisysnode__handlers__query_identity --> urisys_node__packages__python__urisysnode__identity__load_pairing
    urisys_node__packages__python__urisysnode__handlers__command_indicator_on --> urisys_node__packages__python__urisysnode__identity__require_paired
    urisys_node__packages__python__urisysnode__handlers__command_indicator_on --> urisys_node__packages__python__urisysnode__identity__set_remote_control
    urisys_node__packages__python__urisysnode__handlers__command_indicator_off --> urisys_node__packages__python__urisysnode__identity__require_paired
    urisys_node__packages__python__urisysnode__handlers__command_indicator_off --> urisys_node__packages__python__urisysnode__identity__set_remote_control
    urisys_node__packages__python__urisysnode__handlers__query_packs --> urisys_node__packages__python__urisysnode__pack_resolver__auto_install_enabled
    urisys_node__packages__python__urisysnode__handlers__command_install_pack --> urisys_node__packages__python__urisysnode__serve__load_pack_into_runtime
    urisys_node__packages__python__urisysnode__handlers__command_register_forward --> urisys_node__packages__python__urisysnode__serve__register_forward_pack
    urisys_node__packages__python__urisysnode__router__resolve_remote_route --> urisys_node__packages__python__urisysnode__router___match_pattern
    urisys_node__packages__python__urisysnode__display_bootstrap___agent_up --> urisys_node__packages__python__urisysnode__display_bootstrap___agent_url
    urisys_node__packages__python__urisysnode__display_bootstrap___screencast_ready --> urisys_node__packages__python__urisysnode__display_bootstrap___agent_url
    urisys_node__packages__python__urisysnode__display_bootstrap___start_agent --> urisys_node__packages__python__urisysnode__display_bootstrap___agent_up
    urisys_node__packages__python__urisysnode__display_bootstrap___start_screencast --> urisys_node__packages__python__urisysnode__display_bootstrap___screencast_ready
    urisys_node__packages__python__urisysnode__display_bootstrap___start_screencast --> urisys_node__packages__python__urisysnode__display_bootstrap___agent_url
    urisys_node__packages__python__urisysnode__display_bootstrap__bootstrap_wayland_capture --> urisys_node__packages__python__urisysnode__display_bootstrap___ensure_session_env
    urisys_node__packages__python__urisysnode__display_bootstrap__bootstrap_wayland_capture --> urisys_node__packages__python__urisysnode__display_bootstrap___agent_url
    urisys_node__packages__python__urisysnode__display_bootstrap__bootstrap_wayland_capture --> urisys_node__packages__python__urisysnode__display_bootstrap___agent_up
    urisys_node__packages__python__urisysnode__display_bootstrap__bootstrap_wayland_capture --> urisys_node__packages__python__urisysnode__display_bootstrap___start_agent
    urisys_node__packages__python__urisysnode__identity___identity_path --> urisys_node__packages__python__urisysnode__identity___data_dir
    urisys_node__packages__python__urisysnode__identity___pairing_path --> urisys_node__packages__python__urisysnode__identity___data_dir
    urisys_node__packages__python__urisysnode__identity__load_identity --> urisys_node__packages__python__urisysnode__identity___identity_path
    urisys_node__packages__python__urisysnode__identity__load_identity --> urisys_node__packages__python__urisysnode__identity__save_identity
    urisys_node__packages__python__urisysnode__identity__load_identity --> urisys_node__packages__python__urisysnode__identity___hostname
    urisys_node__packages__python__urisysnode__identity__save_identity --> urisys_node__packages__python__urisysnode__identity___identity_path
    urisys_node__packages__python__urisysnode__identity__load_pairing --> urisys_node__packages__python__urisysnode__identity___pairing_path
    urisys_node__packages__python__urisysnode__identity__enroll --> urisys_node__packages__python__urisysnode__identity__load_identity
    urisys_node__packages__python__urisysnode__identity__enroll --> urisys_node__packages__python__urisysnode__identity___pairing_path
    urisys_node__packages__python__urisysnode__identity__save_pairing --> urisys_node__packages__python__urisysnode__identity___pairing_path
    urisys_node__packages__python__urisysnode__identity__set_remote_control --> urisys_node__packages__python__urisysnode__identity__load_pairing
    urisys_node__packages__python__urisysnode__identity__set_remote_control --> urisys_node__packages__python__urisysnode__identity__save_pairing
    urisys_node__packages__python__urisysnode__identity__require_paired --> urisys_node__packages__python__urisysnode__identity__load_pairing
    urisys_node__packages__python__urisysnode__identity__health_payload --> urisys_node__packages__python__urisysnode__identity__load_identity
    urisys_node__packages__python__urisysnode__identity__health_payload --> urisys_node__packages__python__urisysnode__identity__load_pairing
    urisys_node__packages__python__urisysnode__artifact_resolver__fetch_json --> urisys_node__packages__python__urisysnode__artifact_resolver___auth_opener
    urisys_node__packages__python__urisysnode__artifact_resolver__fetch_text --> urisys_node__packages__python__urisysnode__artifact_resolver___auth_opener
    urisys_node__packages__python__urisysnode__artifact_resolver__parse_contract_spec --> urisys_node__packages__python__urisysnode__artifact_resolver___contract_yaml_block
    urisys_node__packages__python__urisysnode__artifact_resolver__contract_spec_from_release --> urisys_node__packages__python__urisysnode__artifact_resolver__contract_url_from_release
    urisys_node__packages__python__urisysnode__artifact_resolver__contract_spec_from_release --> urisys_node__packages__python__urisysnode__artifact_resolver__parse_contract_spec
    urisys_node__packages__python__urisysnode__artifact_resolver__contract_spec_from_release --> urisys_node__packages__python__urisysnode__artifact_resolver__fetch_text
    urisys_node__packages__python__urisysnode__artifact_resolver__load_artifact_index --> urisys_node__packages__python__urisysnode__artifact_resolver__is_url
    urisys_node__packages__python__urisysnode__artifact_resolver__load_artifact_index --> urisys_node__packages__python__urisysnode__artifact_resolver__fetch_json
    urisys_node__packages__python__urisysnode__artifact_resolver__fetch_release --> urisys_node__packages__python__urisysnode__artifact_resolver__fetch_json
    urisys_node__packages__python__urisysnode__artifact_resolver__fetch_release --> urisys_node__packages__python__urisysnode__artifact_resolver__release_api_url
    urisys_node__packages__python__urisysnode__artifact_resolver__resolve_and_run --> urisys_node__packages__python__urisysnode__artifact_resolver__load_artifact_index
    urisys_node__packages__python__urisysnode__artifact_resolver__resolve_and_run --> urisys_node__packages__python__urisysnode__artifact_resolver__load_node_profile
    urisys_node__packages__python__urisysnode__artifact_resolver__resolve_and_run --> urisys_node__packages__python__urisysnode__artifact_resolver__select_artifact
    urisys_node__packages__python__urisysnode__artifact_resolver__resolve_and_run --> urisys_node__packages__python__urisysnode__artifact_resolver__docker_pull
    urisys_node__packages__python__urisysnode__artifact_resolver__resolve_and_run --> urisys_node__packages__python__urisysnode__artifact_resolver__docker_run_worker
    urisys_node__packages__python__urisysnode__artifact_resolver__resolve_and_run --> urisys_node__packages__python__urisysnode__artifact_resolver__wait_health
    urisys_node__packages__python__urisysnode__artifact_resolver__run_release --> urisys_node__packages__python__urisysnode__artifact_resolver__load_artifact_index
    urisys_node__packages__python__urisysnode__artifact_resolver__run_release --> urisys_node__packages__python__urisysnode__artifact_resolver__load_node_profile
    urisys_node__packages__python__urisysnode__artifact_resolver__run_release --> urisys_node__packages__python__urisysnode__artifact_resolver__select_artifact
    urisys_node__packages__python__urisysnode__artifact_resolver__run_release --> urisys_node__packages__python__urisysnode__artifact_resolver__docker_pull
    urisys_node__packages__python__urisysnode__artifact_resolver__run_release --> urisys_node__packages__python__urisysnode__artifact_resolver__docker_run_worker
    urisys_node__packages__python__urisysnode__artifact_resolver__run_release --> urisys_node__packages__python__urisysnode__artifact_resolver__wait_health
    urisys_node__packages__python__urisysnode__artifact_resolver__resolve_from_release --> urisys_node__packages__python__urisysnode__artifact_resolver__fetch_release
    urisys_node__packages__python__urisysnode__artifact_resolver__resolve_from_release --> urisys_node__packages__python__urisysnode__artifact_resolver__run_release
    urisys_node__packages__python__urishell__handlers___mock --> urisys_node__packages__python__urishell__handlers___detect_display
    urisys_node__packages__python__urishell__handlers__shell_run --> urisys_node__packages__python__urishell__handlers___detect_display
    urisys_node__packages__python__urishell__handlers__shell_run --> urisys_node__packages__python__urishell__handlers___mock
    urisys_node__packages__python__urisysnode__pack_resolver__github_wheel_url --> urisys_node__packages__python__urisysnode__pack_resolver__github_owner
    urisys_node__packages__python__urisysnode__pack_resolver__resolve_pack_spec --> urisys_node__packages__python__urisysnode__pack_resolver__github_wheel_url
