flowchart TD
%% generated in 0.01s
    packages__python["packages.python<br/>22 funcs"]
    src__urisys["src.urisys<br/>81 funcs"]
    uribrowser_docker__packages["uribrowser-docker.packages<br/>9 funcs"]
    urienv_docker__packages["urienv-docker.packages<br/>29 funcs"]
    urikvm_docker__packages["urikvm-docker.packages<br/>44 funcs"]
    urikvm_docker__scripts["urikvm-docker.scripts<br/>5 funcs"]
    urirdp_docker__packages["urirdp-docker.packages<br/>60 funcs"]
    uristepper_docker__packages["uristepper-docker.packages<br/>63 funcs"]
    urisys_automation_lab__server["urisys-automation-lab.server<br/>17 funcs"]
    urisys_node__packages["urisys-node.packages<br/>67 funcs"]
    urikvm_docker__packages ==>|7| packages__python
    urirdp_docker__packages ==>|6| packages__python
    urisys_node__packages ==>|4| uristepper_docker__packages
    urienv_docker__packages -->|3| uristepper_docker__packages
    urirdp_docker__packages -->|2| uristepper_docker__packages
    uribrowser_docker__packages -->|2| uristepper_docker__packages
    urikvm_docker__packages -->|2| uristepper_docker__packages
    packages__python -->|2| urienv_docker__packages
    urirdp_docker__packages -->|1| urisys_node__packages
    urirdp_docker__packages -->|1| urienv_docker__packages
    uribrowser_docker__packages -->|1| urienv_docker__packages
    urikvm_docker__packages -->|1| urisys_node__packages
    urikvm_docker__packages -->|1| urienv_docker__packages
    urikvm_docker__scripts -->|1| uristepper_docker__packages
    urienv_docker__packages -->|1| src__urisys
    urisys_automation_lab__server -->|1| uristepper_docker__packages
