"""Markpact compile pipeline."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable

import yaml

from .models import CompiledMarkpact, MarkpactError
from .artifacts import write_flows, write_modules, write_protos
from .blocks import handler_blocks, load_yaml_blocks
from .cache import (
    compile_context,
    compiled_from_cache,
    ensure_importable,
    write_compile_metadata,
    write_manifest_flows,
)
from .handlers import write_handler_modules
from .manifest import compile_manifest


def _write_tests_block(ctx: dict[str, Any], blocks: list[Any]) -> None:
    tests = load_yaml_blocks(blocks, "tests")
    if tests:
        ctx["tests_path"].write_text(
            yaml.safe_dump(tests[0], sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
    else:
        ctx["tests_path"] = None


def _write_docs_block(ctx: dict[str, Any], blocks: list[Any]) -> None:
    docs = [b.content.strip() for b in blocks if b.kind == "docs"]
    if docs:
        ctx["docs_path"].write_text("\n\n".join(docs) + "\n", encoding="utf-8")
    else:
        ctx["docs_path"] = None


def _existing_path(p: Path | None) -> Path | None:
    return p if isinstance(p, Path) and p.exists() else None


class MarkpactCompiler:
    """Compile one-file Markpacts into cached runtime artifacts."""

    def __init__(self, cache_root: str | Path) -> None:
        self.cache_root = Path(cache_root)

    def compile(
        self,
        path: str | Path,
        *,
        out_dir: str | Path | None = None,
        force: bool = False,
        validate: Callable[[str | Path], dict[str, Any]],
    ) -> CompiledMarkpact:
        ctx = compile_context(path, cache_root=self.cache_root, out_dir=out_dir)
        blocks = ctx["blocks"]
        if ctx["manifest_path"].exists() and not force:
            return compiled_from_cache(ctx, blocks)

        validation = validate(ctx["source_path"])
        if not validation["ok"]:
            raise MarkpactError("; ".join(validation.get("warnings") or ["Markpact validation failed."]))

        ctx["cache_dir"].mkdir(parents=True, exist_ok=True)
        ctx["package_dir"].mkdir(parents=True, exist_ok=True)
        (ctx["package_dir"] / "__init__.py").write_text(
            "# generated by urisys Markpact compiler\n",
            encoding="utf-8",
        )

        write_handler_modules(ctx["package_dir"], handler_blocks(blocks))
        manifest = compile_manifest(
            ctx["pack"],
            package_id=ctx["package_id"],
            module_name=ctx["module_name"],
            source_hash=ctx["digest"],
        )
        ctx["manifest_path"].write_text(
            yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )

        _write_tests_block(ctx, blocks)
        _write_docs_block(ctx, blocks)

        flows_dir, flow_ids = write_flows(ctx["cache_dir"], blocks)
        if flows_dir and flow_ids:
            write_manifest_flows(ctx["manifest_path"], flows_dir, list(flow_ids))
        proto_dir, proto_files = write_protos(ctx["cache_dir"], blocks)
        module_files = write_modules(ctx["cache_dir"], blocks)
        write_compile_metadata(ctx)
        ensure_importable(ctx["cache_dir"])

        return CompiledMarkpact(
            source_path=ctx["source_path"],
            source_hash=ctx["digest"],
            cache_dir=ctx["cache_dir"],
            package_id=ctx["package_id"],
            module_name=ctx["module_name"],
            manifest_path=ctx["manifest_path"],
            tests_path=_existing_path(ctx["tests_path"]),
            docs_path=_existing_path(ctx["docs_path"]),
            metadata_path=ctx["metadata_path"],
            flows_dir=flows_dir,
            flow_ids=flow_ids,
            proto_dir=proto_dir,
            proto_files=proto_files,
            module_files=module_files,
        )


__all__ = ["MarkpactCompiler"]
