def register(runtime):
    runtime.register(
        "urimail://{account}/query/status",
        "python://urimail.handlers:status",
        kind="query",
        operation="mail.status",
    )
    runtime.register(
        "urimail://{account}/inbox/query/unread",
        "python://urimail.handlers:inbox_unread",
        kind="query",
        operation="mail.inbox.unread",
    )
    runtime.register(
        "urimail://{account}/message/command/compose",
        "python://urimail.handlers:message_compose",
        kind="command",
        operation="mail.message.compose",
        approval="required",
        side_effects=True,
    )
    runtime.register(
        "urimail://{account}/message/command/send",
        "python://urimail.handlers:message_send",
        kind="command",
        operation="mail.message.send",
        approval="required",
        side_effects=True,
    )
    runtime.register(
        "urimail://{account}/message/command/publish-post",
        "python://urimail.handlers:message_publish_post",
        kind="command",
        operation="mail.message.publish_post",
        approval="required",
        side_effects=True,
    )
