"""Generate a UriContract Markpact from a runtime ``manifest.yaml`` and detect
drift between the two.

``manifest.yaml`` (read by ``urisysedge.manifest.register_manifest_file``) is the
single source of truth a pack ships for runtime registration. The UriContract
Markpact is the *spec* surface of the same capabilities. Keeping both hand-written
guarantees drift; this module derives the contract from the manifest and compares
an existing contract against it.

Field mapping (manifest -> contract):

    manifest.id                         -> metadata.id      ("<id>.contract")
    manifest.version                    -> metadata.version (normalised to semver)
    manifest.scheme                     -> scheme
    uri_patterns[kind==query]           -> queries[]   {id, pattern}
    uri_patterns[kind==command]         -> commands[]  {id, pattern, side_effects,
                                                        requires_approval}
    uri_patterns[].operation            -> <entry>.id
    uri_patterns[].approval == required -> requires_approval: true
    manifest.uses                       -> uses[]   (passed through if present)
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from .markpact_models import MarkpactError

API_VERSION = "urisys.io/v1"


def load_manifest(path: str | Path) -> dict[str, Any]:
    data = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise MarkpactError(f"{path}: manifest must be a YAML mapping.")
    return data


def normalize_version(version: Any) -> str:
    """Normalise a manifest version (int ``1`` or ``"0.1.0"``) to semver text."""
    if version is None:
        return "0.0.0"
    text = str(version).strip()
    if not text:
        return "0.0.0"
    parts = text.split(".")
    if all(p.isdigit() for p in parts):
        while len(parts) < 3:
            parts.append("0")
        return ".".join(parts[:3])
    return text


def contract_id(manifest: dict[str, Any]) -> str:
    base = str(manifest.get("id") or "").strip()
    if not base:
        raise MarkpactError("manifest.id is required to derive a contract id.")
    return base if base.endswith(".contract") else f"{base}.contract"


def _routes(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    raw = manifest.get("uri_patterns") or []
    if not isinstance(raw, list):
        raise MarkpactError("manifest.uri_patterns must be a list.")
    return [item for item in raw if isinstance(item, dict)]


def _entry(item: dict[str, Any], *, command: bool) -> dict[str, Any]:
    operation = str(item.get("operation") or item.get("id") or "").strip()
    pattern = str(item.get("pattern") or item.get("uri") or "").strip()
    if not operation or not pattern:
        raise MarkpactError(f"uri_pattern entry requires operation and pattern: {item!r}")
    entry: dict[str, Any] = {"id": operation, "pattern": pattern}
    if command:
        entry["side_effects"] = bool(item.get("side_effects", True))
        entry["requires_approval"] = str(item.get("approval", "required")) == "required"
    return entry


def manifest_to_contract(manifest: dict[str, Any]) -> dict[str, Any]:
    scheme = str(manifest.get("scheme") or "").strip()
    if not scheme:
        raise MarkpactError("manifest.scheme is required.")
    queries: list[dict[str, Any]] = []
    commands: list[dict[str, Any]] = []
    for item in _routes(manifest):
        kind = str(item.get("kind") or ("command" if "/command/" in str(item.get("pattern", "")) else "query"))
        if kind == "command":
            commands.append(_entry(item, command=True))
        else:
            queries.append(_entry(item, command=False))

    contract: dict[str, Any] = {
        "apiVersion": API_VERSION,
        "kind": "UriContract",
        "metadata": {"id": contract_id(manifest), "version": normalize_version(manifest.get("version"))},
        "scheme": scheme,
    }
    if queries:
        contract["queries"] = queries
    if commands:
        contract["commands"] = commands
    uses = manifest.get("uses")
    if isinstance(uses, list) and uses:
        contract["uses"] = list(uses)
    return contract


def render_contract_markpact(manifest: dict[str, Any], *, title: str | None = None) -> str:
    contract = manifest_to_contract(manifest)
    heading = title or f"UriContract: {manifest.get('id', contract['metadata']['id'])}"
    body = yaml.safe_dump(contract, sort_keys=False, allow_unicode=True).rstrip("\n")
    note = "<!-- generated by `urisys markpact gen-contract` from manifest.yaml; do not edit by hand. -->"
    return f"# {heading}\n\n{note}\n\n```yaml markpact:contract\n{body}\n```\n"


def load_contract_block(path: str | Path) -> dict[str, Any]:
    """Extract the ``markpact:contract`` YAML mapping from a Markpact file."""
    from .markpact_manager import MarkpactManager

    blocks = MarkpactManager().read_blocks(path)
    contract_blocks = [b for b in blocks if b.kind == "contract" and b.lang in {"yaml", "yml"}]
    if len(contract_blocks) != 1:
        raise MarkpactError(f"{path}: expected exactly one ```yaml markpact:contract``` block, found {len(contract_blocks)}.")
    data = yaml.safe_load(contract_blocks[0].content) or {}
    if not isinstance(data, dict):
        raise MarkpactError(f"{path}: markpact:contract block must contain a YAML mapping.")
    return data


def _by_pattern(entries: Any) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for item in entries or []:
        if isinstance(item, dict) and item.get("pattern"):
            out[str(item["pattern"])] = item
    return out


def diff_manifest_contract(manifest: dict[str, Any], contract: dict[str, Any]) -> list[str]:
    """Return a list of drift messages; empty list means manifest and contract agree."""
    expected = manifest_to_contract(manifest)
    issues: list[str] = []

    if expected["scheme"] != contract.get("scheme"):
        issues.append(f"scheme: manifest {expected['scheme']!r} != contract {contract.get('scheme')!r}")

    exp_meta, got_meta = expected["metadata"], contract.get("metadata") or {}
    if exp_meta["id"] != got_meta.get("id"):
        issues.append(f"metadata.id: expected {exp_meta['id']!r}, got {got_meta.get('id')!r}")
    if exp_meta["version"] != normalize_version(got_meta.get("version")):
        issues.append(f"metadata.version: manifest {exp_meta['version']!r} != contract {got_meta.get('version')!r}")

    for section in ("queries", "commands"):
        exp = _by_pattern(expected.get(section))
        got = _by_pattern(contract.get(section))
        for pattern in sorted(set(exp) - set(got)):
            issues.append(f"{section}: pattern {pattern!r} present in manifest but missing in contract")
        for pattern in sorted(set(got) - set(exp)):
            issues.append(f"{section}: pattern {pattern!r} present in contract but missing in manifest")
        for pattern in sorted(set(exp) & set(got)):
            e, g = exp[pattern], got[pattern]
            if e["id"] != g.get("id"):
                issues.append(f"{section} {pattern!r}: id manifest {e['id']!r} != contract {g.get('id')!r}")
            if section == "commands":
                if bool(e.get("side_effects")) != bool(g.get("side_effects")):
                    issues.append(f"commands {pattern!r}: side_effects manifest {e.get('side_effects')} != contract {g.get('side_effects')}")
                if bool(e.get("requires_approval")) != bool(g.get("requires_approval")):
                    issues.append(f"commands {pattern!r}: requires_approval manifest {e.get('requires_approval')} != contract {g.get('requires_approval')}")

    exp_uses = set(expected.get("uses") or [])
    got_uses = set(contract.get("uses") or [])
    if exp_uses != got_uses:
        if exp_uses - got_uses:
            issues.append(f"uses: manifest declares {sorted(exp_uses - got_uses)} missing in contract")
        if got_uses - exp_uses and exp_uses:
            issues.append(f"uses: contract declares {sorted(got_uses - exp_uses)} missing in manifest")
    return issues
